"""Email sending via SMTP."""

import logging
import smtplib
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import Optional, List

logger = logging.getLogger(__name__)


class EmailSender:
    """Sends email reports via SMTP."""

    def __init__(self, config):
        """Initialize email sender.

        Args:
            config: Configuration object
        """
        self.config = config
        email_config = config.email_config

        self.smtp_server = email_config['smtp_server']
        self.smtp_port = email_config['smtp_port']
        self.sender_email = email_config['sender_email']
        self.sender_password = email_config['sender_password']
        self.recipient_email = email_config['recipient_email']
        self.subject_prefix = email_config['subject_prefix']

    def send_report(
        self,
        html_file: Path,
        ris_file: Optional[Path] = None,
        subject: Optional[str] = None
    ) -> bool:
        """Send email report with attachments.

        Args:
            html_file: Path to HTML report file
            ris_file: Optional path to RIS file
            subject: Optional custom subject line

        Returns:
            True if sent successfully, False otherwise
        """
        try:
            # Read HTML content
            with open(html_file, 'r', encoding='utf-8') as f:
                html_content = f.read()

            # Create email
            msg = self._create_email(
                html_content=html_content,
                subject=subject,
                ris_file=ris_file
            )

            # Send email
            logger.info(f"Sending email to {self.recipient_email}...")

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            logger.info("Email sent successfully!")
            return True

        except Exception as e:
            logger.error(f"Error sending email: {e}", exc_info=True)
            return False

    def _create_email(
        self,
        html_content: str,
        subject: Optional[str],
        ris_file: Optional[Path]
    ) -> MIMEMultipart:
        """Create email message.

        Args:
            html_content: HTML email body
            subject: Email subject
            ris_file: Optional RIS attachment

        Returns:
            MIMEMultipart message
        """
        # Create message
        msg = MIMEMultipart('alternative')

        # Set headers
        if not subject:
            from datetime import datetime
            subject = f"LLM Research Digest - {datetime.now().strftime('%b %d, %Y')}"

        msg['Subject'] = f"{self.subject_prefix} {subject}"
        msg['From'] = self.sender_email
        msg['To'] = self.recipient_email

        # Add HTML body
        html_part = MIMEText(html_content, 'html')
        msg.attach(html_part)

        # Add RIS attachment if provided
        if ris_file and ris_file.exists():
            self._attach_file(msg, ris_file)

        return msg

    def _attach_file(self, msg: MIMEMultipart, file_path: Path):
        """Attach file to email.

        Args:
            msg: Email message
            file_path: Path to file to attach
        """
        try:
            with open(file_path, 'rb') as f:
                attachment = MIMEBase('application', 'octet-stream')
                attachment.set_payload(f.read())

            encoders.encode_base64(attachment)
            attachment.add_header(
                'Content-Disposition',
                f'attachment; filename="{file_path.name}"'
            )

            msg.attach(attachment)
            logger.debug(f"Attached file: {file_path.name}")

        except Exception as e:
            logger.error(f"Error attaching file {file_path}: {e}")

    def send_test_email(self) -> bool:
        """Send a test email to verify configuration.

        Returns:
            True if successful
        """
        html_content = """
        <html>
            <body>
                <h2>🧪 Test Email</h2>
                <p>This is a test email from LLM News Digest Agent.</p>
                <p>If you received this, your email configuration is working correctly!</p>
                <hr>
                <p style="color: #666; font-size: 12px;">
                    Generated by LLM News Digest Agent
                </p>
            </body>
        </html>
        """

        msg = MIMEMultipart()
        msg['Subject'] = f"{self.subject_prefix} Test Email"
        msg['From'] = self.sender_email
        msg['To'] = self.recipient_email
        msg.attach(MIMEText(html_content, 'html'))

        try:
            logger.info("Sending test email...")

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            logger.info("✓ Test email sent successfully!")
            return True

        except Exception as e:
            logger.error(f"✗ Failed to send test email: {e}", exc_info=True)
            return False
